_target_: submit_pi0_jobs.Pi0RealTowelSpatial

hydra:
  run:
    dir: .
  output_subdir: null
run_method: main
cfg_name: real_towel_pi0_spatial_group

x_strat: group

sample_real_strat: uniform
real_data_nums: [0,20,40,60,80,100]
num_train_points: 4
num_per_instance: 20
num_instances: 3
k_factor: 2
data_ready: false
train_ready: false
run_baseline_equal: true
run_baseline_remix: false
dry_run: false

combos:
  - [tt, lt]
  - [cp, dis]
  - [op, dq]

slope_num_factors: [1,2,3]