_target_: submit_dp_jobs.DPSimBase

hydra:
  run:
    dir: .
  output_subdir: null

run_method: main
cfg_name: sim_pick_dp_visual_group_dataset_ablation1

x_strat: group
sample_sim_strat: uniform
sim_data_nums: [0,10,20,30,50,130]
num_train_points: 4
num_per_instance: 20
num_instances: 4
k_factor: 2
data_ready: false
train_ready: false
run_baseline_equal: true
run_baseline_remix: false
dry_run: false
combos:
  - [tt, lt]
  - [cp, dis]
  - [bg, tt]

slope_num_factors: [2,4]