_target_: submit_dp_jobs.DPSimPegVisual

hydra:
  run:
    dir: .
  output_subdir: null


run_method: main
cfg_name: sim_peg_insertion_dp_visual_group_ablation_300

x_strat: group
sample_sim_strat: uniform
sim_data_nums: [0,40,80,120,140,220]
num_train_points: 4
num_per_instance: 35
num_instances: 4
k_factor: 2
data_ready: false
train_ready: false
run_baseline_equal: true
run_baseline_remix: false
dry_run: false
combos:   
- [tt, lt]
- [cp, dis]
- [bg, cp]

slope_num_factors: [5]