defaults:
  - _self_

grasp:
  num_action_candidates: 1
  max_pushin_dist: 0.05
  min_pushin_dist: -0.01


rrt:
  rnd: 1
  replay_with_controller: true
  smooth_iter: 10
  data_iter: 1
  save_video: True
  rrt_iter: 100
  traj_path: null
  traj_idx: 3
