defaults:
  - aug: random_rot
  - feature_aggregation: avgpool
  - _self_

_target_: guided_dc.policy.obs_encoder.MultiviewObsEncoder
img_model_name: resnet
img_cond_steps: ${task.img_cond_steps}
num_views: ${task.num_views}
img_size: ${task.img_size}
share_img_model: False
obs_dim: ${eval:'${task.obs_dim} * ${task.cond_steps}'}

obs_strat: concat
post_proc_dropout: 0
feat_norm: null
token_dim: null
cond_mlp_dims: null

# timm only
pretrained: false
frozen: false
use_lora: false
lora_rank: 8
use_group_norm: True
